### ISSUE TITLE
Wrong result at the South Pole

### ISSUE THREAD

**Issue by All4Gis** [gadomski/antimeridian#124]
Hi
First of all congratulations for this great library.

I am doing some tests with data crossing the north and south poles and it seems that with the data crossing the south pole the result is wrong, more specifically the result is crossing the north pole.

Here is an example:
This is the original data  [SP_nosplit.json](https://github.com/user-attachments/files/16106916/SP_nosplit.json)

![Captura de pantalla 2024-07-05 a las 10 08 18](https://github.com/gadomski/antimeridian/assets/8123225/afc79030-fd64-4505-bbce-77ec367bf2fc)

The expected result is this:

![Captura de pantalla 2024-07-05 a las 10 08 44](https://github.com/gadomski/antimeridian/assets/8123225/67f4201d-ea77-447c-b602-80d1810cada1)

But the library is giving me back just the opposite.

![Captura de pantalla 2024-07-05 a las 10 09 32](https://github.com/gadomski/antimeridian/assets/8123225/37d7ed2e-0ba2-4926-b956-5d48ba4d026d)

I have been testing with this library too and for example it recognizes correctly when it crosses the north or south pole.

https://pypi.org/project/footprint-facility/. , the code is in https://pypi.org/project/footprint-facility/#files

Do you have any idea what can happen, I guess the key is in the extend_over_poles function, can it be?
I am investigating it and if I find the solution I will send you a PR, but if you have any idea what is happening.

A quick solution would be to perform a subtraction, but obviously this is not a good practice.

    geom = shapely.geometry.shape(shape)   
    world_Polygon = Polygon([[-180, 90], [180, 90], [180, -90], [-180, -90]])
    sp = _check_contains_south_pole(geom)
    p =  fix_polygon(
                geom,
                force_north_pole=force_north_pole,
                force_south_pole=force_south_pole,
                fix_winding=fix_winding,
            )
    if(sp or force_south_pole):
        p = world_Polygon.difference(p)

Cheers
Fran Raga

**Comment by gadomski** [comment]
Hey @All4Gis, thanks for the report, glad to hear the repository has been useful. There's a couple of things going on here.

First, your polygon is "wound" incorrectly to cover the south pole. This library assumes that incoming polygons are wound counter-clockwise, and only handles clockwise-wound polygons in some cases (see https://github.com/gadomski/antimeridian/pull/39 and https://github.com/gadomski/antimeridian/issues/33 for some previous discussion on this topic). The polygon you provided is wound in a way that indicates that it _should_ cover the north pole, i.e. its x coordinates are increasing:

![original](https://github.com/user-attachments/assets/b483e24b-7cff-4d33-8692-d2fe5477e9e6)

For my algorithm to work out-of-the-box, you could reverse the order of the coordinates. Alternatively, you _should_ be able to use the `--force-south-pole` command line argument or `force_south_pole=True` Python argument, but it turns out that was broken ... I've opened https://github.com/gadomski/antimeridian/pull/125 to fix that issue. Once that fix is released, you should be able to do

```shell
antimeridian fix SP_nosplit.json --force-south-pole
```

to get the result you want.

Let me know if that makes sense, and if the `force-south-pole` fix helps!

**Comment by gadomski** [comment]
Fix released in v0.3.8: https://pypi.org/project/antimeridian/0.3.8/

**Comment by All4Gis** [comment]
It seems that it does not work well in all cases, for example with this one:
[nosplit_2.json](https://github.com/user-attachments/files/16249776/nosplit_2.json)
<img width="714" alt="Captura de pantalla 2024-07-16 a las 15 39 59" src="https://github.com/user-attachments/assets/23828e1a-758a-4ee6-b48e-faf40b2beeaf">

The expected resylt would be:
<img width="670" alt="Captura de pantalla 2024-07-16 a las 15 38 53" src="https://github.com/user-attachments/assets/49357606-12e9-4c8a-8757-f7beff56d261">


But it returns this:
<img width="686" alt="Captura de pantalla 2024-07-16 a las 15 40 16" src="https://github.com/user-attachments/assets/da0533d2-88fc-41f6-9abc-d84f5fadbb81">


I will investigate the code, and see if I can help, and not just ask, hehehe. Thanks

**Comment by All4Gis** [comment]
Forget my last comment, I had a error with the projection that I'm using, the result is as expected.
